name: Free macOS Runner

on:
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-latest

    steps:
      - name: Check macOS and Xcode
        run: |
          sw_vers
          xcodebuild -version
          xcode-select -p
